= Kubernetes/OpenShift NFS Server

The goal of this project is to create a NFS Server container on top of Kubernetes/OpenShift. This is helpful when we need a quick RWX volume. I use it for demo only.

- [x] Install NFS on container
- [x] Generate PVs using bash
- [x] Create persistent option
- [ ] Use NFS provisioner 

== Pre-req

=== Create project and set permission

[source,bash]
----
oc new-project nfs-server
oc adm policy add-scc-to-user privileged -z default -n nfs-server
----

== Installing

=== Deploying NFS Server Ephemeral

To deploy a NFS Server ephemeral (using emptyDir), run:

[source,bash]
----
oc apply -f https://raw.githubusercontent.com/gojeaqui/kubernetes-nfs/master/nfs-server-ephemeral.yml -n nfs-server
----

=== Deploying NFS Server Persistent

To deploy a NFS Server persistent (using PV), run:

[source,bash]
----
# Create pvc for NFS
oc apply -f https://raw.githubusercontent.com/gojeaqui/kubernetes-nfs/master/nfs-server-persistent.yml -n nfs-server
----

=== Creating PVs for the cluster

We'll need the ClusterIp of our NFS Server to use it in our PVs. We can get it by running the following command:

[source,bash]
----
NFS_CLUSTER_IP=$(oc -n nfs-server get svc/nfs-server-alpine -o=jsonpath='{.spec.clusterIP}')

# Now make sure the var NFS_CLUSTER_IP contains the cluster ip:
echo $NFS_CLUSTER_IP

# Now install all PVs by running:
curl https://raw.githubusercontent.com/gojeaqui/kubernetes-nfs/master/persistent-volumes.yml | sed "s/REPLACEME/$NFS_CLUSTER_IP/g"  | oc apply -f -
----

==== OPTIONAL

You can create the PVs file in your local machine:

[source,bash]
----
# Create 100 PVs 100Gi
for i in {0..100}; do

cat <<EOF >> /tmp/persistent-volume-tmp.yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv$i
spec:
  capacity:
    storage: 100Gi
  nfs:
    server: $NFS_CLUSTER_IP
    path: /pv$i
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
---
EOF

done

# Create all PVs
kubectl apply -f /tmp/persistent-volume-tmp.yml
----

== Clean up

=== Removing NFS Server

[source,bash]
----
kubectl delete deploy/nfs-server-alpine -n nfs-server
kubectl delete svc/nfs-server-alpine -n nfs-server
kubectl delete pvc/nfs-pvc -n nfs-server
----

=== Removing PVs

[source,bash]
----
for i in {0..100}; do
  kubectl delete pv/pv$i
done
----